name: CI Pipeline

# When the workflow runs
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Check if package.json exists
      run: |
        if [ -f "package.json" ]; then
          echo "package.json found"
        else
          echo "package.json not found, creating a basic one"
          cat > package.json << EOF
        {
          "name": "git-hub-action",
          "version": "1.0.0",
          "scripts": {
            "test": "echo 'No tests specified' && exit 0"
          }
        }
        EOF
        fi
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
